# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_facebook_connectable}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonas Grimfelt"]
  s.date = %q{2009-12-07}
  s.description = %q{Devise << Facebook Connect.}
  s.email = %q{grimen@gmail.com}
  s.extra_rdoc_files = [
    "Rakefile",
     "assets/javascripts/facebook_connect_helper.js",
     "lib/devise_facebook_connectable.rb",
     "lib/devise_facebook_connectable/controller_filters.rb",
     "lib/devise_facebook_connectable/locales/en.yml",
     "lib/devise_facebook_connectable/model.rb",
     "lib/devise_facebook_connectable/routes.rb",
     "lib/devise_facebook_connectable/schema.rb",
     "lib/devise_facebook_connectable/strategy.rb",
     "lib/devise_facebook_connectable/view_helpers.rb"
  ]
  s.files = [
    "Rakefile",
     "assets/javascripts/facebook_connect_helper.js",
     "lib/devise_facebook_connectable.rb",
     "lib/devise_facebook_connectable/controller_filters.rb",
     "lib/devise_facebook_connectable/locales/en.yml",
     "lib/devise_facebook_connectable/model.rb",
     "lib/devise_facebook_connectable/routes.rb",
     "lib/devise_facebook_connectable/schema.rb",
     "lib/devise_facebook_connectable/strategy.rb",
     "lib/devise_facebook_connectable/view_helpers.rb"
  ]
  s.homepage = %q{http://github.com/grimen/devise_facebook_connectable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Devise << Facebook Connect.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
